[package]
name = "rustboard-api"
version = "0.1.0"
edition = "2024"

[dependencies]
# Web framework
axum = "0.8"

# Serialization
serde = { version = "1", features = ["derive"] }

# Async runtime
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread"] }

# UUID generation
uuid = { version = "1", features = ["v4"] }
