[package]
name = "rustboard-api"
version = "0.2.1"
edition = "2024"

[dependencies]
anyhow = "1"
# Async-await support
async-trait = "0.1"

# Web framework
axum = "0.8"

# 날짜/시간
chrono = { version = "0.4", features = ["serde"] }

# configuration
config = "0.15"
regex = "1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# 데이터베이스
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "chrono"] }

# error handling
thiserror = "2"

# Async runtime
tokio = { version = "1", features = ["macros", "parking_lot", "rt-multi-thread"] }


# Middleware
tower = "0.5"
tower-http = { version = "0.7", features = ["compression-gzip", "cors", "timeout", "trace"] }
tower_governor = "0.8"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Swagger
utoipa = {version = "5", features = ["chrono"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }

