[workspace]
resolver = "3"
members = [
  "api",
  "domain",
  "notifier",
  "proto",
]

[workspace.dependencies]
# 오류
anyhow = "1"
# ARGON2 해싱
argon2 = "0.5"
# Async-await support
async-trait = "0.1"
# Web framework
axum = { version = "0.8", features = ["ws"] }
# 날짜/시간
chrono = { version = "0.4", features = ["serde"] }
# configuration
config = "0.15"
# futures_util
futures-util = "0.3"
# JWT
jsonwebtoken = { version = "11", features = ["rust_crypto"] }
# OpenTelemetry
opentelemetry = "0.32"
opentelemetry-otlp = { version = "0.32", features = ["grpc-tonic"] }
opentelemetry_sdk = "0.32"
opentelemetry-semantic-conventions = "0.32"
# 해싱
password-hash = { version = "0.6", features = ["getrandom"] }
# Protocol Buffer
prost = "0.14"
# 정규 표현식
regex = "1"
# 민감한 정보 로깅 방지
secrecy = { version = "0.10", features = ["serde"] }
# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# 데이터베이스
sqlx = { version = "0.8", features = ["chrono", "postgres", "runtime-tokio"] }
# error handling
thiserror = "2"
# Async runtime
tokio = { version = "1", features = ["io-util", "macros", "parking_lot", "rt-multi-thread", "signal", "time"] }
# gRPC
tonic = "0.14"
tonic-prost = "0.14"
# Middleware
tower = "0.5"
tower_governor = "0.8"
tower-http = { version = "0.7", features = ["compression-gzip", "cors", "timeout", "trace"] }
# Logging
tracing = "0.1"
tracing-opentelemetry = "0.33"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
# Swagger
utoipa = { version = "5", features = ["chrono"] }
utoipa-axum = "0.2"
utoipa-swagger-ui = { version = "9", features = ["axum"] }
# UUID
uuid = { version = "1", features = ["v4"] }

### 테스트용 크레이트
# JSON 구조 검사
insta = { version = "1", features = ["json", "redactions"] }
# http 요청
reqwest = { version = "0.13", features = ["json"] }
tokio-stream = "0.1.19"
# WS 클라이언트
tokio-tungstenite = { version = "0.30", features = ["tokio-rustls"] }

### 빌드용 크레이트
tonic-prost-build = "0.14"

### 워크스페이스 라이브러리
# domain
rustboard-domain = { path = "domain" }
# notifier
rustboard-notifier = { path = "notifier" }
# proto
rustboard-proto = { path = "proto" }
