[package]
name = "rustboard-api"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
argon2.workspace = true
axum.workspace = true
chrono.workspace = true
futures-util.workspace = true
jsonwebtoken.workspace = true
opentelemetry.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tonic.workspace = true
tower.workspace = true
tower_governor.workspace = true
tower-http.workspace = true
tracing.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
uuid.workspace = true

rustboard-domain.workspace = true
rustboard-proto.workspace = true

[dev-dependencies]
insta.workspace = true
reqwest.workspace = true
tokio-tungstenite.workspace = true
tonic.workspace = true

rustboard-notifier.workspace = true
